// SPDX-License-Identifier: BUSL-1.1
import {z} from 'zod';
import {aiProcessSchema,aiWorkloadSchema,hardwareSchema} from './intelligence';
const metric=z.number().finite().nonnegative();
const percent=z.number().finite().min(0).max(100);
const smallString=z.string().max(256);
export const processSchema=z.object({pid:z.number().int().positive(),name:smallString,app:smallString,cpu:metric,memory:metric,project:smallString.nullable(),ports:z.array(z.number().int().min(1).max(65535)).max(256),diskReadRate:metric.optional(),diskWriteRate:metric.optional(),networkInRate:metric.optional(),networkOutRate:metric.optional(),networkSockets:z.number().int().nonnegative().optional(),ai:aiProcessSchema.optional()});
export const portMappingSchema=z.object({hostPort:z.number().int().min(1).max(65535).nullable(),containerPort:z.number().int().min(1).max(65535),protocol:z.enum(['tcp','udp','sctp'])});
export const runtimeNames=['docker','podman'] as const;
export const containerSchema=z.object({runtime:z.enum(runtimeNames),id:z.string().min(1).max(128),name:smallString,image:z.string().max(512),state:z.string().max(64),cpu:metric,memory:metric,memoryLimit:metric.nullable(),netIn:metric,netOut:metric,ports:z.array(portMappingSchema).max(256)});
export const runtimeStatusSchema=z.object({name:z.enum(runtimeNames),available:z.boolean(),error:smallString.nullable()});
export const inventorySchema=z.object({agentVersion:z.string().max(64),hostname:smallString,architecture:z.string().max(64),platform:z.string().max(64),platformRelease:z.string().max(128),python:z.string().max(64),tools:z.record(z.string().max(64),z.string().max(256)).optional(),macOS:z.string().max(64).optional(),model:z.string().max(128).optional()});
export const agentHealthSchema=z.object({version:z.string().max(64),uptimeSeconds:metric,samples:z.number().int().nonnegative(),failures:z.number().int().nonnegative(),healthy:z.boolean()});
export const snapshotSchema=z.object({version:z.literal(1),timestamp:z.string().datetime(),host:z.object({name:smallString,os:smallString,cores:z.number().int().positive(),memoryTotal:metric.positive()}),cpu:percent,memoryUsed:metric,diskUsed:metric,diskTotal:metric.positive(),download:metric,upload:metric,battery:percent.nullable(),processes:z.array(processSchema).max(20000),containers:z.array(containerSchema).max(2000).optional(),runtimes:z.array(runtimeStatusSchema).max(8).optional(),hardware:hardwareSchema.optional(),aiWorkloads:z.array(aiWorkloadSchema).max(128).optional(),inventory:inventorySchema.optional(),agent:agentHealthSchema.optional()}).refine(s=>s.memoryUsed<=s.host.memoryTotal&&s.diskUsed<=s.diskTotal,{message:'Used memory/disk must not exceed capacity'});
export type Snapshot=z.infer<typeof snapshotSchema>;
export type Container=z.infer<typeof containerSchema>;
export type RuntimeStatus=z.infer<typeof runtimeStatusSchema>;
export type AppGroup={name:string,cpu:number,memory:number,processes:Snapshot['processes'],ports:number[],project:string|null};
export function groupApps(s:Snapshot):AppGroup[]{const groups=new Map<string,AppGroup>();for(const p of s.processes){const key=p.app;const g=groups.get(key)||{name:key,cpu:0,memory:0,processes:[],ports:[],project:p.project};g.cpu+=p.cpu;g.memory+=p.memory;g.processes.push(p);g.ports=[...new Set([...g.ports,...p.ports])];groups.set(key,g);}return [...groups.values()];}
export function runningContainers(s:Snapshot){return(s.containers??[]).filter(c=>c.state.toLowerCase()==='running');}
export function formatPort(p:Container['ports'][number]){return p.hostPort?`${p.hostPort}→${p.containerPort}/${p.protocol}`:`${p.containerPort}/${p.protocol}`;}
export type Platform='macos'|'linux'|'other';
export function macMajor(os:string):number{const m=/(?:macos|mac os x?)\s*(\d+)/i.exec(os);return m?Number(m[1]):0;}
export function platformOf(os:string):Platform{const o=os.toLowerCase();if(o.includes('darwin')||o.includes('macos'))return'macos';if(o.includes('linux'))return'linux';return'other';}
const GB=1024**3,MB=1024**2;
function demoContainers(t:number):Container[]{const rows=[['docker','a1b2c3d4e5f6','postgres','postgres:16-alpine','running',2.4,412*MB,2*GB,[[5432,5432]]],['docker','b2c3d4e5f6a1','redis','redis:7-alpine','running',.6,18*MB,512*MB,[[6379,6379]]],['docker','c3d4e5f6a1b2','web','nginx:alpine','running',.3,9*MB,null,[[8080,80]]],['podman','d4e5f6a1b2c3','ml-worker','ghcr.io/zyvor/ml-worker:1.4','running',38.5,1.6*GB,4*GB,[]],['podman','e5f6a1b2c3d4','grafana','grafana/grafana:11','exited',0,0,null,[[3000,3000]]]] as const;return rows.map(([runtime,id,name,image,state,cpu,memory,memoryLimit,ports],i)=>({runtime,id,name,image,state,cpu:state==='running'?Math.max(0,cpu+Math.sin(t/3+i)*cpu*.25):0,memory,memoryLimit,netIn:state==='running'?(120+t*3+i*40)*MB:0,netOut:state==='running'?(40+t+i*12)*MB:0,ports:ports.map(([hostPort,containerPort])=>({hostPort,containerPort,protocol:'tcp' as const}))}));}
export function demoSnapshot(t=0):Snapshot {const apps=[['Google Chrome',18.4,5.2,24],['Visual Studio Code',6.8,2.1,12],['Docker',4.2,3.6,8],['python',12.7,1.8,4],['node',3.1,.72,5],['Slack',1.2,.48,7],['Terminal',.4,.22,3],['Zyvor Netra',2.1,.34,2]] as const;return {version:1,timestamp:new Date().toISOString(),host:{name:'zyvor-dev-01',os:'Linux · Ubuntu 24.04',cores:16,memoryTotal:32*GB},cpu:Math.max(0,Math.min(100,42+Math.sin(t/3)*8)),memoryUsed:(15.3+Math.sin(t/7)*.4)*GB,diskUsed:316*GB,diskTotal:512*GB,download:(3.4+Math.sin(t/4))*1024**2,upload:.82*1024**2,battery:null,processes:apps.flatMap(([app,cpu,memory,count],a)=>Array.from({length:count},(_,i)=>({pid:1000+a*100+i,name:i===0?app:`${app} helper`,app,cpu:(cpu+Math.sin(t/4+a)*1.2)/count,memory:memory*GB/count,project:a===3?'ml-inference':a===4?'zyvor-dashboard':null,ports:i===0&&a===3?[8000]:i===0&&a===4?[5173]:[],...(i===0&&a===3?{diskReadRate:128*1024,diskWriteRate:64*1024,networkInRate:2*MB,networkOutRate:4*MB,networkSockets:12,ai:{engine:'vLLM',kind:'inference' as const,confidence:98,markers:['vllm']}}:{})}))),aiWorkloads:[{engine:'vLLM',kind:'inference' as const,processes:1,cpu:12.7,memory:1.8*GB,diskReadRate:128*1024,diskWriteRate:64*1024,confidence:98}],inventory:{agentVersion:'0.4.0',hostname:'zyvor-dev-01',architecture:'x86_64',platform:'Linux',platformRelease:'6.8.0',python:'3.13'},agent:{version:'0.4.0',uptimeSeconds:3600,samples:1800,failures:0,healthy:true},containers:demoContainers(t),runtimes:[{name:'docker',available:true,error:null},{name:'podman',available:true,error:null}]};}
export function bytes(v:number){if(v>=GB)return(v/GB).toFixed(1)+' GB';if(v>=MB)return(v/MB).toFixed(1)+' MB';if(v>=1024)return(v/1024).toFixed(1)+' KB';return Math.round(v)+' B';}
