#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Install the Vytrix collector as a per-user launchd agent on macOS.
# The access token is generated once and kept in the login Keychain.
#
#   scripts/install-macos.sh [--allow-origin URL]... [--port N] [--no-containers] [--dry-run]
#   scripts/install-macos.sh --uninstall [--dry-run]
#   scripts/install-macos.sh --show-token
set -euo pipefail

LABEL="com.zyvor.vytrix"
APP_DIR="$HOME/Library/Application Support/Vytrix"
LOG_DIR="$HOME/Library/Logs/Vytrix"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
DB="$APP_DIR/history.sqlite"
SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/agent/vytrix.py"

DRY_RUN=0 UNINSTALL=0 SHOW_TOKEN=0 PORT=9847 CONTAINERS=1
ORIGINS=()

usage() { sed -n '3,9p' "$0" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }
while [[ $# -gt 0 ]]; do
  case "$1" in
    --allow-origin) ORIGINS+=("${2:?--allow-origin needs a value}"); shift 2 ;;
    --port) PORT="${2:?--port needs a value}"; shift 2 ;;
    --no-containers) CONTAINERS=0; shift ;;
    --uninstall) UNINSTALL=1; shift ;;
    --show-token) SHOW_TOKEN=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage 0 ;;
    *) echo "Unknown option: $1" >&2; usage 2 ;;
  esac
done

run() { if [[ $DRY_RUN == 1 ]]; then printf '[dry-run]'; printf ' %q' "$@"; echo; else "$@"; fi; }
write_file() { # path mode <<content
  local path="$1" mode="$2" content; content="$(cat)"
  if [[ $DRY_RUN == 1 ]]; then echo "[dry-run] write $path (mode $mode)"; printf '%s\n' "$content" | sed 's/^/    /'; return; fi
  umask 077; printf '%s\n' "$content" > "$path"; chmod "$mode" "$path"
}
xml_escape() { local s="$1"; s="${s//&/&amp;}"; s="${s//</&lt;}"; s="${s//>/&gt;}"; printf '%s' "$s"; }

if [[ "$(uname -s)" != "Darwin" && $DRY_RUN == 0 ]]; then
  echo "This installer is for macOS. On Linux use scripts/install-linux.sh." >&2; exit 1
fi

if [[ $SHOW_TOKEN == 1 ]]; then
  security find-generic-password -a "$USER" -s "$LABEL" -w; exit
fi

if [[ $UNINSTALL == 1 ]]; then
  run launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
  run rm -f "$PLIST"
  run rm -rf "$APP_DIR/vytrix.py" "$APP_DIR/run.sh"
  run security delete-generic-password -a "$USER" -s "$LABEL" >/dev/null 2>&1 || true
  echo "Vytrix agent removed. History kept in: $DB (delete it manually if unwanted)."
  exit 0
fi

find_python() {
  local candidate
  for candidate in "$(command -v python3 || true)" /opt/homebrew/bin/python3 /usr/local/bin/python3 /usr/bin/python3; do
    [[ -n "$candidate" && -x "$candidate" ]] || continue
    if "$candidate" -c 'import sys; sys.exit(sys.version_info < (3, 10))' 2>/dev/null; then echo "$candidate"; return; fi
  done
  return 1
}
PYTHON="$(find_python)" || { echo "Python 3.10+ is required. Install it with: brew install python" >&2; exit 1; }

[[ ${#ORIGINS[@]} -gt 0 ]] || ORIGINS=("http://localhost:5173")
for origin in "${ORIGINS[@]}"; do
  [[ "$origin" =~ ^https?://[^/]+$ ]] || { echo "Invalid origin '$origin': use an exact origin such as https://dash.example.com" >&2; exit 2; }
done
[[ "$PORT" =~ ^[0-9]+$ && "$PORT" -ge 1 && "$PORT" -le 65535 ]] || { echo "Invalid port: $PORT" >&2; exit 2; }

run mkdir -p "$APP_DIR" "$LOG_DIR" "$(dirname "$PLIST")"
run chmod 700 "$APP_DIR"
run install -m 0644 "$SRC" "$APP_DIR/vytrix.py"

if [[ $DRY_RUN == 1 ]]; then
  echo "[dry-run] generate token and store it in the login Keychain as service '$LABEL'"
elif ! security find-generic-password -a "$USER" -s "$LABEL" >/dev/null 2>&1; then
  TOKEN="$("$PYTHON" -c 'import secrets; print(secrets.token_urlsafe(32))')"
  security add-generic-password -U -a "$USER" -s "$LABEL" -l "Vytrix collector token" -w "$TOKEN"
  NEW_TOKEN=1
fi

ARGS=(--port "$PORT" --database "$DB")
for origin in "${ORIGINS[@]}"; do ARGS+=(--allow-origin "$origin"); done
[[ $CONTAINERS == 1 ]] || ARGS+=(--no-containers)
QUOTED_ARGS="$(printf ' %q' "${ARGS[@]}")"

write_file "$APP_DIR/run.sh" 0700 <<EOF
#!/bin/bash
# Generated by scripts/install-macos.sh. Reads the token from the login Keychain at start.
set -euo pipefail
export VYTRIX_TOKEN="\$(/usr/bin/security find-generic-password -a "\$(/usr/bin/id -un)" -s "$LABEL" -w)"
exec "$PYTHON" "$APP_DIR/vytrix.py"$QUOTED_ARGS
EOF

write_file "$PLIST" 0644 <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key>
  <array><string>/bin/bash</string><string>$(xml_escape "$APP_DIR/run.sh")</string></array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key><string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$(xml_escape "$HOME/.docker/bin"):/Applications/Docker.app/Contents/Resources/bin:/opt/podman/bin</string>
  </dict>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>ThrottleInterval</key><integer>10</integer>
  <key>ProcessType</key><string>Background</string>
  <key>LowPriorityIO</key><true/>
  <key>Nice</key><integer>5</integer>
  <key>StandardOutPath</key><string>$(xml_escape "$LOG_DIR/collector.log")</string>
  <key>StandardErrorPath</key><string>$(xml_escape "$LOG_DIR/collector.log")</string>
</dict>
</plist>
EOF

[[ $DRY_RUN == 1 ]] || plutil -lint "$PLIST" >/dev/null
run launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
run launchctl bootstrap "gui/$(id -u)" "$PLIST"

if [[ $DRY_RUN == 1 ]]; then echo; echo "Dry run complete: nothing was changed."; exit 0; fi
echo
echo "Vytrix collector installed as launchd agent '$LABEL'."
echo "  Endpoint : http://127.0.0.1:$PORT/v1/snapshot (loopback only)"
echo "  Origins  : ${ORIGINS[*]}"
echo "  Logs     : $LOG_DIR/collector.log"
echo "  Python   : $PYTHON"
if [[ ${NEW_TOKEN:-0} == 1 ]]; then
  echo "  Token    : $TOKEN"
  echo "             (stored in the login Keychain; show again with: $0 --show-token)"
else
  echo "  Token    : unchanged; show with: $0 --show-token"
fi
